/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.OperacionesControlador;

/**
 *
 * @author Laboratorios DCCO
 */
public class operacionesVista extends javax.swing.JFrame {

    /**
     * Creates new form operacionesVista
     */
    public operacionesVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_2 = new javax.swing.JTextField();
        op_suma = new javax.swing.JRadioButton();
        op_resta = new javax.swing.JRadioButton();
        op_multiplicar = new javax.swing.JRadioButton();
        op_dividir = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("INGRESE NUMERO 1: ");

        txt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_1ActionPerformed(evt);
            }
        });

        jLabel2.setText("INGRESE NUMERO 2: ");

        op_suma.setText("SUMAR");
        op_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumar(evt);
            }
        });

        op_resta.setText("RESTAR");
        op_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restar(evt);
            }
        });

        op_multiplicar.setText("MULTIPLICAR");
        op_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicar(evt);
            }
        });

        op_dividir.setText("DIVIDIR");
        op_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                division(evt);
            }
        });

        jLabel3.setText("RESULTADO: ");

        lbl_resultado.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txt_2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(txt_1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(op_resta)
                            .addComponent(op_multiplicar)
                            .addComponent(op_dividir)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_resultado))
                            .addComponent(op_suma))))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op_suma)
                .addGap(18, 18, 18)
                .addComponent(op_resta)
                .addGap(18, 18, 18)
                .addComponent(op_multiplicar)
                .addGap(18, 18, 18)
                .addComponent(op_dividir)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_resultado))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_1ActionPerformed

    private void restar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restar
OperacionesControlador opcontrolador = new OperacionesControlador();

int num1= Integer.parseInt(txt_1.getText());
int num2 =Integer.parseInt(txt_2.getText());
int resultado = opcontrolador.restar(num1,num2);

lbl_resultado.setText(String.valueOf(resultado));

    }//GEN-LAST:event_restar

    private void sumar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumar
// captura de datos
OperacionesControlador opcontrolador = new OperacionesControlador();

int num1= Integer.parseInt(txt_1.getText());
int num2 =Integer.parseInt(txt_2.getText());
int resultado = opcontrolador.sumar(num1,num2);

lbl_resultado.setText(String.valueOf(resultado));

    }//GEN-LAST:event_sumar

    private void multiplicar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicar
/*
        int num1= Integer.parseInt(txt_1.getText());
int num2= Integer.parseInt(txt_2.getText());
int resultado = opcontrolador.restar(num2, num2);
lbl_resultado.setText(String.valueOf(resultado));
  */

OperacionesControlador opcontrolador = new OperacionesControlador();

int num1= Integer.parseInt(txt_1.getText());
int num2 =Integer.parseInt(txt_2.getText());
int resultado = opcontrolador.multiplicar(num1,num2);

lbl_resultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_multiplicar

    private void division(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_division
OperacionesControlador opcontrolador = new OperacionesControlador();

int num1= Integer.parseInt(txt_1.getText());
int num2 =Integer.parseInt(txt_2.getText());
int resultado = opcontrolador.dividir(num1,num2);

lbl_resultado.setText(String.valueOf(resultado));
            }//GEN-LAST:event_division

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(operacionesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(operacionesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(operacionesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(operacionesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new operacionesVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JRadioButton op_dividir;
    private javax.swing.JRadioButton op_multiplicar;
    private javax.swing.JRadioButton op_resta;
    private javax.swing.JRadioButton op_suma;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_2;
    // End of variables declaration//GEN-END:variables
}
